spring:
  application:
    name: portal
  profiles:
    active: netposa

server:
  port: 8081
  
logging:
  file: ./logs/centerconf/netposa-portal.log

endpoints:
  health:
    sensitive: false
management:
  security:
    enabled: false
  health:
    status:
      order: DOWN, OUT_OF_SERVICE, UP, UNKNOWN


