spring:
  application:
    name: apollo-portal
  profiles:
    active: netposa

server:
  port: 8080
  
logging:
  file: ./apollo-portal.log

endpoints:
  health:
    sensitive: false
management:
  security:
    enabled: false
  health:
    status:
      order: DOWN, OUT_OF_SERVICE, UNKNOWN, UP 


